// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: lock.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LockRequest 代表所有的請求輸入
type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	TtlSec        int32                  `protobuf:"varint,3,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_lock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{0}
}

func (x *LockRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LockRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LockRequest) GetTtlSec() int32 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

// LockResponse 代表鎖的資訊
type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiredAt     int64                  `protobuf:"varint,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_lock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{1}
}

func (x *LockResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LockResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LockResponse) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

// ActionResponse 代表單純的操作結果
type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_lock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_lock_proto_rawDescGZIP(), []int{2}
}

func (x *ActionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_lock_proto protoreflect.FileDescriptor

const file_lock_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"lock.proto\x12\x02pb\"N\n" +
	"\vLockRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x17\n" +
	"\attl_sec\x18\x03 \x01(\x05R\x06ttlSec\"U\n" +
	"\fLockResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\x03R\texpiredAt\"(\n" +
	"\x0eActionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x9a\x01\n" +
	"\vLockService\x12,\n" +
	"\aAcquire\x12\x0f.pb.LockRequest\x1a\x10.pb.LockResponse\x12.\n" +
	"\aRelease\x12\x0f.pb.LockRequest\x1a\x12.pb.ActionResponse\x12-\n" +
	"\x06Extend\x12\x0f.pb.LockRequest\x1a\x12.pb.ActionResponseB\x10Z\x0elockservice/pbb\x06proto3"

var (
	file_lock_proto_rawDescOnce sync.Once
	file_lock_proto_rawDescData []byte
)

func file_lock_proto_rawDescGZIP() []byte {
	file_lock_proto_rawDescOnce.Do(func() {
		file_lock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lock_proto_rawDesc), len(file_lock_proto_rawDesc)))
	})
	return file_lock_proto_rawDescData
}

var file_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lock_proto_goTypes = []any{
	(*LockRequest)(nil),    // 0: pb.LockRequest
	(*LockResponse)(nil),   // 1: pb.LockResponse
	(*ActionResponse)(nil), // 2: pb.ActionResponse
}
var file_lock_proto_depIdxs = []int32{
	0, // 0: pb.LockService.Acquire:input_type -> pb.LockRequest
	0, // 1: pb.LockService.Release:input_type -> pb.LockRequest
	0, // 2: pb.LockService.Extend:input_type -> pb.LockRequest
	1, // 3: pb.LockService.Acquire:output_type -> pb.LockResponse
	2, // 4: pb.LockService.Release:output_type -> pb.ActionResponse
	2, // 5: pb.LockService.Extend:output_type -> pb.ActionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lock_proto_init() }
func file_lock_proto_init() {
	if File_lock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lock_proto_rawDesc), len(file_lock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lock_proto_goTypes,
		DependencyIndexes: file_lock_proto_depIdxs,
		MessageInfos:      file_lock_proto_msgTypes,
	}.Build()
	File_lock_proto = out.File
	file_lock_proto_goTypes = nil
	file_lock_proto_depIdxs = nil
}
